# Generated by Django 3.2 on 2025-10-04 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_alumni', '0002_auto_20251003_0252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumni',
            options={'verbose_name_plural': 'Alumni'},
        ),
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name_plural': 'Batches'},
        ),
    ]
