# Generated by Django 3.2 on 2025-10-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
