# Generated by Django 3.1.4 on 2025-10-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='faculty/photos')),
                ('role', models.CharField(choices=[('head', 'Department Head'), ('faculty', 'Faculty Member'), ('staff', 'Office Staff')], default='faculty', max_length=20)),
            ],
        ),
    ]
