# Generated by Django 3.1.4 on 2025-10-02 19:20

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_auto_20251002_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
