# Generated by Django 3.1.4 on 2025-10-02 19:48

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_faculty_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('thumb', models.ImageField(blank=True, null=True, upload_to='labs/thumbs')),
                ('images', models.ImageField(blank=True, null=True, upload_to='labs/images')),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('thumb', models.ImageField(blank=True, null=True, upload_to='projects/thumbs')),
                ('images', models.ImageField(blank=True, null=True, upload_to='projects/images')),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
