# Generated by Django 3.1.4 on 2025-10-02 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_lab_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='images',
        ),
        migrations.RemoveField(
            model_name='project',
            name='images',
        ),
    ]
