# Generated by Django 3.1.4 on 2025-10-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_auto_20251003_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='thumb',
        ),
        migrations.RemoveField(
            model_name='project',
            name='thumb',
        ),
        migrations.AddField(
            model_name='lab',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='labs/thumbnails'),
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='projects/thumbnails'),
        ),
    ]
