# Generated by Django 3.1.4 on 2025-10-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0006_auto_20251003_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='summary',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='summary',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
