# Generated by Django 3.1.4 on 2025-10-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0007_auto_20251003_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='summary',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
