# Generated by Django 3.1.4 on 2022-01-18 20:36

import app_alumni.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_alumni', '0002_auto_20211219_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='session',
        ),
        migrations.AlterField(
            model_name='alumni',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show in homepage or not.'),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_name', models.CharField(max_length=200)),
                ('session', models.CharField(help_text='Eg: 2012 - 13', max_length=10, validators=[app_alumni.validators.BatchSessionValidator])),
                ('total_students', models.IntegerField(default=0)),
                ('batch_pictures', models.ManyToManyField(blank=True, related_name='_batch_batch_pictures_+', to='app_alumni.Picture')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='alumni',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_alumni.batch'),
        ),
    ]
