# Generated by Django 3.1.4 on 2022-01-27 12:56

import app_alumni.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_alumni', '0003_auto_20220119_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='registration_number',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[app_alumni.validators.RegistrationNumberValidator]),
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='batch',
            name='session',
            field=models.CharField(help_text='Eg: 2012-13', max_length=10, unique=True, validators=[app_alumni.validators.BatchSessionValidator]),
        ),
    ]
