# Generated by Django 3.1.4 on 2022-02-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_alumni', '0004_auto_20220127_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='passing_year',
        ),
        migrations.AddField(
            model_name='alumni',
            name='graduation_year',
            field=models.CharField(default=2022, max_length=4),
            preserve_default=False,
        ),
    ]
