# Generated by Django 3.1.4 on 2022-03-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_alumni', '0005_auto_20220216_0238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumni',
            old_name='birth_of_date',
            new_name='date_of_birth',
        ),
        migrations.AlterField(
            model_name='alumni',
            name='registration_number',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='session',
            field=models.CharField(help_text='Eg: 2012-13', max_length=10, unique=True),
        ),
    ]
