# Generated by Django 3.1.4 on 2022-03-29 09:08

import app_alumni.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_alumni', '0006_auto_20220328_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Format: YYYY-MM-DD', null=True, validators=[app_alumni.validators.RegistrationNumberValidator]),
        ),
        migrations.AlterField(
            model_name='batch',
            name='session',
            field=models.CharField(help_text='Eg: 2012-13', max_length=10, unique=True, validators=[app_alumni.validators.BatchSessionValidator]),
        ),
    ]
